id: I2AA9E08E
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T00:58:35.599258'
last_modified: '2022-06-19T00:58:35.599274'
parser: null
source_metadata:
  title: Hevajra Abhisamaya by Chos rgyal Phags pa (1235–1280), block print, colophon
    excerpt
  author: འཕགས་པ་བློ་གྲོས་རྒྱལ་མཚན།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2015-06-24);
    revised, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/944
  bases:
    003b:
      title: Hevajra Abhisamaya by Chos rgyal Phags pa (1235–1280), block print, colophon
        excerpt
      order: 1
      base_file: 003b.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
